# backend/music_links.py
# 30 YouTube links per mood. Edit to your taste.
# Keep them as plain strings; the API will pick a random subset per request.

YT_MUSIC_MAP = {
    "joy": [
        "https://www.youtube.com/watch?v=d-diB65scQU",  # Pharrell - Happy
        "https://www.youtube.com/watch?v=ru0K8uYEZWw",  # JT - Can't Stop The Feeling!
        "https://www.youtube.com/watch?v=OPf0YbXqDm0",  # Uptown Funk
        "https://www.youtube.com/watch?v=fLexgOxsZu0",  # Good Time
        "https://www.youtube.com/watch?v=KQ6zr6kCPj8",  # Party Rock Anthem
        "https://www.youtube.com/watch?v=32sYGCOYJUM",  # Best Day Of My Life
        "https://www.youtube.com/watch?v=ZbZSe6N_BXs",  # Happy (Live)
        "https://www.youtube.com/watch?v=wyx6JDQCslE",  # Dynamite (Taio Cruz)
        "https://www.youtube.com/watch?v=HgzGwKwLmgM",  # Don't Stop Me Now
        "https://www.youtube.com/watch?v=0yW7w8F2TVA",  # Rather Be
        "https://www.youtube.com/watch?v=JGwWNGJdvx8",  # Shape of You
        "https://www.youtube.com/watch?v=YQHsXMglC9A",  # Hello (energizing vocals)
        "https://www.youtube.com/watch?v=7PCkvCPvDXk",  # All About That Bass
        "https://www.youtube.com/watch?v=iPUmE-tne5U",  # Walking on Sunshine
        "https://www.youtube.com/watch?v=IPXIgEAGe4U",  # Señorita
        "https://www.youtube.com/watch?v=09R8_2nJtjg",  # Sugar
        "https://www.youtube.com/watch?v=UwuAPyOImoI",  # Good as Hell
        "https://www.youtube.com/watch?v=K0ibBPhiaG0",  # On Top of the World
        "https://www.youtube.com/watch?v=PT2_F-1esPk",  # Closer
        "https://www.youtube.com/watch?v=34Na4j8AVgA",  # Finesse (Remix)
        "https://www.youtube.com/watch?v=4NRXx6U8ABQ",  # Blinding Lights
        "https://www.youtube.com/watch?v=7wtfhZwyrcc",  # Thunder
        "https://www.youtube.com/watch?v=0KSOMA3QBU0",  # Roar
        "https://www.youtube.com/watch?v=YQ5vI8ZC0sM",  # Can't Hold Us
        "https://www.youtube.com/watch?v=YQJr3gCBXU8",  # High Hopes
        "https://www.youtube.com/watch?v=nfWlot6h_JM",  # Shake It Off
        "https://www.youtube.com/watch?v=bfWk4P2xpiw",  # Geronimo
        "https://www.youtube.com/watch?v=CMNry4PE93Y",  # Hey Ya!
        "https://www.youtube.com/watch?v=450p7goxZqg",  # Happy Now? (Kygo)
        "https://www.youtube.com/watch?v=lqYQXIt4SpA"   # Best Friend
    ],
    "sadness": [
        "https://www.youtube.com/watch?v=RB-RcX5DS5A",  # Coldplay - Fix You
        "https://www.youtube.com/watch?v=4N3N1MlvVc4",  # Mad World
        "https://www.youtube.com/watch?v=0put0_a--Ng",  # Adele - Someone Like You
        "https://www.youtube.com/watch?v=uelHwf8o7_U",  # Love The Way You Lie
        "https://www.youtube.com/watch?v=pY9b6jgbNyc",  # Let Her Go
        "https://www.youtube.com/watch?v=8UVNT4wvIGY",  # Somebody That I Used To Know
        "https://www.youtube.com/watch?v=5anLPw0Efmo",  # Back To Black
        "https://www.youtube.com/watch?v=2RryUYYO9n8",  # Skinny Love
        "https://www.youtube.com/watch?v=hLQl3WQQoQ0",  # Someone Like You (alt)
        "https://www.youtube.com/watch?v=Ni-5uO3j6i8",  # Breathe Me
        "https://www.youtube.com/watch?v=cnVjkE87FDY",  # When I Was Your Man
        "https://www.youtube.com/watch?v=50VNCymT-Cs",  # The Night We Met
        "https://www.youtube.com/watch?v=QJO3ROT-A4E",  # Little Things
        "https://www.youtube.com/watch?v=1SiylvmFI_8",  # Say Something
        "https://www.youtube.com/watch?v=0G2VxhV_gXM",  # My Immortal
        "https://www.youtube.com/watch?v=RBumgq5yVrA",  # A Thousand Years
        "https://www.youtube.com/watch?v=3JWTaaS7LdU",  # I Will Always Love You
        "https://www.youtube.com/watch?v=q0hyYWKXF0Q",  # Someone You Loved
        "https://www.youtube.com/watch?v=ekzHIouo8Q4",  # The A Team
        "https://www.youtube.com/watch?v=2Vv-BfVoq4g",  # Perfect
        "https://www.youtube.com/watch?v=450p7goxZqg",  # Happy Now? (bittersweet)
        "https://www.youtube.com/watch?v=TUVcZfQe-Kw",  # Levitating (uplift)
        "https://www.youtube.com/watch?v=YQHsXMglC9A",  # Hello
        "https://www.youtube.com/watch?v=fLexgOxsZu0",  # Good Time (reset)
        "https://www.youtube.com/watch?v=UceaB4D0jpo",  # Sunflower (gentle)
        "https://www.youtube.com/watch?v=uelHwf8o7_U",  # LV Way You Lie (alt)
        "https://www.youtube.com/watch?v=fJ9rUzIMcZQ",  # Bohemian Rhapsody
        "https://www.youtube.com/watch?v=kXYiU_JCYtU",  # Numb
        "https://www.youtube.com/watch?v=J_ub7Etch2U",  # Everything I Wanted
        "https://www.youtube.com/watch?v=0yW7w8F2TVA"   # Rather Be (reset)
    ],
    "anger": [
        "https://www.youtube.com/watch?v=JwYX52BP2Sk",  # Killing In The Name
        "https://www.youtube.com/watch?v=YVkUvmDQ3HY",  # In The End
        "https://www.youtube.com/watch?v=WNFeohWlA9M",  # Duality
        "https://www.youtube.com/watch?v=eVTXPUF4Oz4",  # Numb (alt)
        "https://www.youtube.com/watch?v=8j741TUIET0",  # Believer
        "https://www.youtube.com/watch?v=hTWKbfoikeg",  # Smells Like Teen Spirit
        "https://www.youtube.com/watch?v=CdqoNKCCt7A",  # Eye of the Tiger
        "https://www.youtube.com/watch?v=ktvTqknDobU",  # Radioactive
        "https://www.youtube.com/watch?v=fLexgOxsZu0",  # Good Time (cool down)
        "https://www.youtube.com/watch?v=Qzx0B3mP4Ew",  # Centuries
        "https://www.youtube.com/watch?v=7wtfhZwyrcc",  # Thunder (release)
        "https://www.youtube.com/watch?v=O-zpOMYRi0w",  # The Phoenix
        "https://www.youtube.com/watch?v=LBr7kECsjcQ",  # Demons
        "https://www.youtube.com/watch?v=JkK8g6FMEXE",  # Lose Yourself
        "https://www.youtube.com/watch?v=DLzxrzFCyOs",  # Never Gonna Give You Up (pattern break 😉)
        "https://www.youtube.com/watch?v=rYEDA3JcQqw",  # Rolling in the Deep
        "https://www.youtube.com/watch?v=YBHQbu5rbdQ",  # Stronger
        "https://www.youtube.com/watch?v=pRpeEdMmmQ0",  # Waka Waka
        "https://www.youtube.com/watch?v=9bZkp7q19f0",  # Gangnam Style (pattern break)
        "https://www.youtube.com/watch?v=VbfpW0pbvaU",  # Roar (alt)
        "https://www.youtube.com/watch?v=0J2QdDbelmY",  # Seven Nation Army
        "https://www.youtube.com/watch?v=DUT5rEU6pqM",  # Stressed Out
        "https://www.youtube.com/watch?v=kXYiU_JCYtU",  # Numb
        "https://www.youtube.com/watch?v=2vjPBrBU-TM",  # Chandelier
        "https://www.youtube.com/watch?v=NHozn0YXAeE",  # Titanium
        "https://www.youtube.com/watch?v=uelHwf8o7_U",  # Love The Way You Lie
        "https://www.youtube.com/watch?v=2A2XBoxtcUA",  # Bad Blood
        "https://www.youtube.com/watch?v=YQHsXMglC9A",  # Hello (belt it out)
        "https://www.youtube.com/watch?v=nfWlot6h_JM",  # Shake It Off (release)
        "https://www.youtube.com/watch?v=6EEW-9NDM5k"   # Stronger (Kelly Clarkson)
    ],
    "fear": [
        "https://www.youtube.com/watch?v=0J2QdDbelmY",  # Seven Nation Army
        "https://www.youtube.com/watch?v=ktvTqknDobU",  # Radioactive
        "https://www.youtube.com/watch?v=450p7goxZqg",  # Happy Now? (calm)
        "https://www.youtube.com/watch?v=y6120QOlsfU",  # Darude - Sandstorm (focus)
        "https://www.youtube.com/watch?v=QJO3ROT-A4E",  # Little Things (soothing)
        "https://www.youtube.com/watch?v=2Vv-BfVoq4g",  # Perfect (calm)
        "https://www.youtube.com/watch?v=2vjPBrBU-TM",  # Chandelier (release)
        "https://www.youtube.com/watch?v=kXYiU_JCYtU",  # Numb (externalize)
        "https://www.youtube.com/watch?v=tAGnKpE4NCI",  # Nothing Else Matters
        "https://www.youtube.com/watch?v=YQJr3gCBXU8",  # High Hopes
        "https://www.youtube.com/watch?v=3tmd-ClpJxA",  # Believer (alt)
        "https://www.youtube.com/watch?v=mWRsgZuwf_8",  # It's Time
        "https://www.youtube.com/watch?v=JGwWNGJdvx8",  # Shape of You (reset)
        "https://www.youtube.com/watch?v=8j741TUIET0",  # Believer
        "https://www.youtube.com/watch?v=0KSOMA3QBU0",  # Roar
        "https://www.youtube.com/watch?v=PT2_F-1esPk",  # Closer
        "https://www.youtube.com/watch?v=4NRXx6U8ABQ",  # Blinding Lights
        "https://www.youtube.com/watch?v=VbfpW0pbvaU",  # Firework
        "https://www.youtube.com/watch?v=ktvTqknDobU",  # Radioactive (dup ok)
        "https://www.youtube.com/watch?v=OPf0YbXqDm0",  # Uptown Funk (reset)
        "https://www.youtube.com/watch?v=nfWlot6h_JM",  # Shake It Off
        "https://www.youtube.com/watch?v=8yis7GzlXNM",  # Weightless (ambient)
        "https://www.youtube.com/watch?v=UfcAVejslrU",  # Buddha Bar (ambient)
        "https://www.youtube.com/watch?v=7NOSDKb0HlU",  # Experience (Ludovico Einaudi)
        "https://www.youtube.com/watch?v=ZV1p3n1k2Nw",  # Clair de Lune
        "https://www.youtube.com/watch?v=QH2-TGUlwu4",  # Nyan Cat (pattern break)
        "https://www.youtube.com/watch?v=Qm846KdZN_c",  # Ambient Study Music
        "https://www.youtube.com/watch?v=6qZQ_8K7KDI",  # Calm Piano
        "https://www.youtube.com/watch?v=4Tr0otuiQuU",  # Moonlight Sonata
        "https://www.youtube.com/watch?v=aWIE0PX1uXk"   # Time - Hans Zimmer
    ],
    "surprise": [
        "https://www.youtube.com/watch?v=KQ6zr6kCPj8",
        "https://www.youtube.com/watch?v=fLexgOxsZu0",
        "https://www.youtube.com/watch?v=0yW7w8F2TVA",
        "https://www.youtube.com/watch?v=i0p1bmr0EmE",
        "https://www.youtube.com/watch?v=izGwDsrQ1eQ",
        "https://www.youtube.com/watch?v=2Vv-BfVoq4g",
        "https://www.youtube.com/watch?v=34Na4j8AVgA",
        "https://www.youtube.com/watch?v=4NRXx6U8ABQ",
        "https://www.youtube.com/watch?v=OPf0YbXqDm0",
        "https://www.youtube.com/watch?v=ru0K8uYEZWw",
        "https://www.youtube.com/watch?v=HgzGwKwLmgM",
        "https://www.youtube.com/watch?v=l9PxOanFjxQ",
        "https://www.youtube.com/watch?v=j5-yKhDd64s",
        "https://www.youtube.com/watch?v=ktvTqknDobU",
        "https://www.youtube.com/watch?v=K0ibBPhiaG0",
        "https://www.youtube.com/watch?v=3AtDnEC4zak",
        "https://www.youtube.com/watch?v=QJO3ROT-A4E",
        "https://www.youtube.com/watch?v=egkSOQA8em8",
        "https://www.youtube.com/watch?v=JGwWNGJdvx8",
        "https://www.youtube.com/watch?v=nfWlot6h_JM",
        "https://www.youtube.com/watch?v=UFCr9QbC1f8",
        "https://www.youtube.com/watch?v=2vjPBrBU-TM",
        "https://www.youtube.com/watch?v=CdqoNKCCt7A",
        "https://www.youtube.com/watch?v=Qm846KdZN_c",
        "https://www.youtube.com/watch?v=2vjPBrBU-TM",
        "https://www.youtube.com/watch?v=IdneKLhsWOQ",
        "https://www.youtube.com/watch?v=azdwsXLmrHE",
        "https://www.youtube.com/watch?v=0KSOMA3QBU0",
        "https://www.youtube.com/watch?v=YVkUvmDQ3HY",
        "https://www.youtube.com/watch?v=ktvTqknDobU"
    ],
    "disgust": [
        "https://www.youtube.com/watch?v=pRpeEdMmmQ0",
        "https://www.youtube.com/watch?v=IdneKLhsWOQ",
        "https://www.youtube.com/watch?v=8j741TUIET0",
        "https://www.youtube.com/watch?v=7wtfhZwyrcc",
        "https://www.youtube.com/watch?v=fLexgOxsZu0",
        "https://www.youtube.com/watch?v=YQHsXMglC9A",
        "https://www.youtube.com/watch?v=kXYiU_JCYtU",
        "https://www.youtube.com/watch?v=PT2_F-1esPk",
        "https://www.youtube.com/watch?v=09R8_2nJtjg",
        "https://www.youtube.com/watch?v=UfcAVejslrU",
        "https://www.youtube.com/watch?v=8yis7GzlXNM",
        "https://www.youtube.com/watch?v=Qm846KdZN_c",
        "https://www.youtube.com/watch?v=0J2QdDbelmY",
        "https://www.youtube.com/watch?v=VbfpW0pbvaU",
        "https://www.youtube.com/watch?v=4NRXx6U8ABQ",
        "https://www.youtube.com/watch?v=E5ONTXHS2mM",
        "https://www.youtube.com/watch?v=ZbZSe6N_BXs",
        "https://www.youtube.com/watch?v=nfWlot6h_JM",
        "https://www.youtube.com/watch?v=2vjPBrBU-TM",
        "https://www.youtube.com/watch?v=2Vv-BfVoq4g",
        "https://www.youtube.com/watch?v=IdneKLhsWOQ",
        "https://www.youtube.com/watch?v=0KSOMA3QBU0",
        "https://www.youtube.com/watch?v=HgzGwKwLmgM",
        "https://www.youtube.com/watch?v=3tmd-ClpJxA",
        "https://www.youtube.com/watch?v=OPf0YbXqDm0",
        "https://www.youtube.com/watch?v=QJO3ROT-A4E",
        "https://www.youtube.com/watch?v=7NOSDKb0HlU",
        "https://www.youtube.com/watch?v=6EEW-9NDM5k",
        "https://www.youtube.com/watch?v=9bZkp7q19f0",
        "https://www.youtube.com/watch?v=JGwWNGJdvx8"
    ],
    "neutral": [
        "https://www.youtube.com/watch?v=VPRjCeoBqrI",
        "https://www.youtube.com/watch?v=UceaB4D0jpo",
        "https://www.youtube.com/watch?v=3JZ4pnNtyxQ",
        "https://www.youtube.com/watch?v=dgLyylpAG8A",
        "https://www.youtube.com/watch?v=Qm846KdZN_c",
        "https://www.youtube.com/watch?v=8yis7GzlXNM",
        "https://www.youtube.com/watch?v=NvR60Wg9R7Q",
        "https://www.youtube.com/watch?v=kXYiU_JCYtU",
        "https://www.youtube.com/watch?v=YQJr3gCBXU8",
        "https://www.youtube.com/watch?v=4NRXx6U8ABQ",
        "https://www.youtube.com/watch?v=OPf0YbXqDm0",
        "https://www.youtube.com/watch?v=2Vv-BfVoq4g",
        "https://www.youtube.com/watch?v=nfWlot6h_JM",
        "https://www.youtube.com/watch?v=0KSOMA3QBU0",
        "https://www.youtube.com/watch?v=ktvTqknDobU",
        "https://www.youtube.com/watch?v=7wtfhZwyrcc",
        "https://www.youtube.com/watch?v=PT2_F-1esPk",
        "https://www.youtube.com/watch?v=0yW7w8F2TVA",
        "https://www.youtube.com/watch?v=fLexgOxsZu0",
        "https://www.youtube.com/watch?v=4Tr0otuiQuU",
        "https://www.youtube.com/watch?v=ZV1p3n1k2Nw",
        "https://www.youtube.com/watch?v=aWIE0PX1uXk",
        "https://www.youtube.com/watch?v=H5v3kku4y6Q",
        "https://www.youtube.com/watch?v=QJO3ROT-A4E",
        "https://www.youtube.com/watch?v=J_ub7Etch2U",
        "https://www.youtube.com/watch?v=UfcAVejslrU",
        "https://www.youtube.com/watch?v=8j741TUIET0",
        "https://www.youtube.com/watch?v=7NOSDKb0HlU",
        "https://www.youtube.com/watch?v=IdneKLhsWOQ",
        "https://www.youtube.com/watch?v=VbfpW0pbvaU"
    ]
}
